version: '3.4'

services:
  seekq.notificationsandmodessettings.api:
    image: ${DOCKER_REGISTRY-}seekqnotificationsandmodessettingsapi
    ports:
      - "32702:80"
    build:
      context: .
      dockerfile: SeekQ.NotificationsAndModesSettings.Api/Dockerfile
    environment:
      ASPNETCORE_ConnectionStrings__MSSQL: "Server=seekq.mssql,1433;Database=SeekQ.NotificationsAndModesSettings;User Id=sa;Password=Password123"

networks:
  default:
    external:
      name: SEEKQ_NETWORK