#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["SeekQ.NotificationsAndModesSettings.Api.Test/SeekQ.NotificationsAndModesSettings.Api.Test.csproj", "SeekQ.NotificationsAndModesSettings.Api.Test/"]
COPY ["SeekQ.NotificationsAndModesSettings.Api/SeekQ.NotificationsAndModesSettings.Api.csproj", "SeekQ.NotificationsAndModesSettings.Api/"]
COPY ["App.Common/App.Common.csproj", "App.Common/"]
RUN dotnet restore "SeekQ.NotificationsAndModesSettings.Api.Test/SeekQ.NotificationsAndModesSettings.Api.Test.csproj"
COPY . .
WORKDIR "/src/SeekQ.NotificationsAndModesSettings.Api.Test"
RUN dotnet build "SeekQ.NotificationsAndModesSettings.Api.Test.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SeekQ.NotificationsAndModesSettings.Api.Test.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SeekQ.NotificationsAndModesSettings.Api.Test.dll"]
