version: '3.4'

services:
  seekq.notificationsandmodessettings.api:
    image: seekqnotificationsandmodessettingsapi:dev
    container_name: SeekQ.NotificationsAndModesSettings.Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "SeekQ.NotificationsAndModesSettings.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_seekq.notificationsandmodessettings.api$
    volumes:
      - D:\OIGALocal\SeekQ1\SeekQ.NotificationsAndModesSettings.Api\SeekQ.NotificationsAndModesSettings.Api:/app
      - D:\OIGALocal\SeekQ1\SeekQ.NotificationsAndModesSettings.Api:/src
      - C:\Users\joseW\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_seekq.notificationsandmodessettings.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_seekq.notificationsandmodessettings.api$ \"/app/bin/Debug/netcoreapp3.1/SeekQ.NotificationsAndModesSettings.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true